# ==========================================
# CHIMERA EXECUTION CONFIGURATION
# ==========================================
import os

# Try loading from secrets.py (ignored by git)
try:
    from .secrets import API_KEY, CLIENT_ID, PASSWORD, TOTP_SECRET
except ImportError:
    # Fallback to Env Vars or Placeholders (Safe for Git)
    API_KEY = os.getenv("ANGLE_API_KEY", "MOCK_API_KEY")
    CLIENT_ID = os.getenv("ANGLE_CLIENT_ID", "MOCK_CLIENT_ID")
    PASSWORD = os.getenv("ANGLE_PASSWORD", "MOCK_PASSWORD")
    TOTP_SECRET = os.getenv("ANGLE_TOTP_SECRET", "MOCK_TOTP")

# --- SYSTEM SETTINGS ---
EXCHANGE = "NSE"
CAPITAL = 100000          # Base capital for allocation calculation
LEVERAGE = 1.0            # Default leverage (Risk Layer may adjust this)
MOCK_MODE = False         # False = LIVE CONNECTION to Angle One

# --- STRATEGY PARAMETERS (FROM CHIMERA ENGINE) ---
TARGET_VOL = 0.15
MAX_LEVERAGE = 1.5
LOOKBACK_GAUSSIAN = 140
LOOKBACK_VP = 60
LOOKBACK_ENERGY = 20

# --- ASSET UNIVERSE ---
INDICES = {
    'BROAD': '^NSEI',     # Nifty 50
    'RISK': '^CNXSC',     # Nifty Smallcap 100 (Canary)
    'FEAR': '^INDIAVIX'   # Volatility
}

TICKERS = [
    'RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 
    'TATAMOTORS.NS', 'SBIN.NS', 'BAJFINANCE.NS', 'ASIANPAINT.NS', 'TITAN.NS',
    'SUNPHARMA.NS', 'JSWSTEEL.NS', 'NTPC.NS', 'POWERGRID.NS', 'ITC.NS',
    'ADANIENT.NS', 'KPITTECH.NS', 'ZOMATO.NS', 'HAL.NS', 'TRENT.NS',
    'BSE.NS', 'CDSL.NS', 'MCX.NS', 'ANGELONE.NS'
]

SAFE_HAVEN = 'GOLDBEES.NS'

# --- SMART EXECUTION PARAMS ---
MAX_ORDER_CHUNK = 0.25    # Maximum % of total order quantity per slice
VOL_SPIKE_THRESHOLD = 0.02 # Volatility level (2%) that triggers scaling down
RETRY_LIMIT = 3           # Number of retries for failed orders
THROTTLE_MIN_DELAY = 0.3  # Min seconds to wait between orders
THROTTLE_MAX_DELAY = 1.2  # Max seconds to wait between orders

# --- PATHS ---
# Path to the signal log generated by Chimera Engine
SIGNAL_LOG_PATH = "../data/chimera_blackbox_final.csv"
